/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.deguzman.hapi2_2_0.register_form;

import com.deguzman.hapi2_2_0.lookup_values.RoleLookupValues;
import com.deguzman.hapi2_2_0.lookup_values.UserStatusLookupValues;
import com.deguzman.hapi2_2_0.menu_main_page.MainMenu;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ejdeg
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        firstnameInputField = new javax.swing.JTextField();
        usernameInputField = new javax.swing.JTextField();
        lastnameInputField = new javax.swing.JTextField();
        passwordInputField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register Form");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(32, 32, 32));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        firstnameInputField.setBackground(new java.awt.Color(40, 40, 40));
        firstnameInputField.setForeground(new java.awt.Color(255, 255, 255));
        firstnameInputField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstnameInputField.setText("Enter First Name");
        firstnameInputField.setToolTipText("Enter First Name");
        firstnameInputField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnameInputFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnameInputFieldFocusLost(evt);
            }
        });

        usernameInputField.setBackground(new java.awt.Color(40, 40, 40));
        usernameInputField.setForeground(new java.awt.Color(255, 255, 255));
        usernameInputField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameInputField.setText("Enter Username");
        usernameInputField.setToolTipText("Enter Username");
        usernameInputField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameInputField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameInputFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameInputFieldFocusLost(evt);
            }
        });

        lastnameInputField.setBackground(new java.awt.Color(40, 40, 40));
        lastnameInputField.setForeground(new java.awt.Color(255, 255, 255));
        lastnameInputField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lastnameInputField.setText("Enter Last Name");
        lastnameInputField.setToolTipText("Enter Last Name");
        lastnameInputField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnameInputFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnameInputFieldFocusLost(evt);
            }
        });

        passwordInputField.setBackground(new java.awt.Color(40, 40, 40));
        passwordInputField.setForeground(new java.awt.Color(255, 255, 255));
        passwordInputField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordInputField.setText("Enter Password");
        passwordInputField.setToolTipText("Enter Password");
        passwordInputField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordInputFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordInputFieldFocusLost(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(40, 40, 40));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton1.setLabel("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cement-wall-texture-background_53876-91519.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cement-wall-texture-background_53876-91519.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstnameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastnameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196))))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(usernameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstnameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastnameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameInputFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameInputFieldFocusGained
        // TODO add your handling code here:
        if (usernameInputField.getText().equals("Enter Username")) {
            usernameInputField.setText("");
            usernameInputField.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_usernameInputFieldFocusGained

    private void usernameInputFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameInputFieldFocusLost
        // TODO add your handling code here:
        if (usernameInputField.getText().equals("")) {
            usernameInputField.setText("Enter Username");
            usernameInputField.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_usernameInputFieldFocusLost

    private void passwordInputFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordInputFieldFocusGained
        // TODO add your handling code here:
        if (passwordInputField.getText().equals("Enter Password")) {
            passwordInputField.setText("");
            passwordInputField.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_passwordInputFieldFocusGained

    private void passwordInputFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordInputFieldFocusLost
        // TODO add your handling code here:
        if (passwordInputField.getText().equals("")) {
            passwordInputField.setText("Enter Password");
            passwordInputField.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_passwordInputFieldFocusLost

    private void firstnameInputFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameInputFieldFocusGained
        // TODO add your handling code here:
        if (firstnameInputField.getText().equals("Enter First Name")) {
            firstnameInputField.setText("");
            firstnameInputField.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_firstnameInputFieldFocusGained

    private void firstnameInputFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameInputFieldFocusLost
        // TODO add your handling code here:
        if (firstnameInputField.getText().equals("")) {
            firstnameInputField.setText("Enter First Name");
            firstnameInputField.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_firstnameInputFieldFocusLost

    private void lastnameInputFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameInputFieldFocusGained
        // TODO add your handling code here:
        if (lastnameInputField.getText().equals("Enter Last Name")) {
            lastnameInputField.setText("");
            lastnameInputField.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_lastnameInputFieldFocusGained

    private void lastnameInputFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameInputFieldFocusLost
        // TODO add your handling code here:
        if (lastnameInputField.getText().equals("")) {
            lastnameInputField.setText("Enter Last Name");
            lastnameInputField.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_lastnameInputFieldFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        final String dbhost = "jdbc:postgresql://localhost:5432/InventoryTrackerDB";
        
        final String dbuser = "postgres";
        
        final String dbpassword = "password";
        
        String username = usernameInputField.getText().toString();
        String password = passwordInputField.getText().toString();
        String firstname = firstnameInputField.getText().toString();
        String lastname = lastnameInputField.getText().toString();
        
        String sql = "INSERT INTO users(username,password,firstname,lastname,role_id,user_status_id) VALUES (?,?,?,?,?,?)";
        
        try {
            Connection connection = DriverManager.getConnection(dbhost,dbuser,dbpassword);
            
            PreparedStatement pst = connection.prepareStatement(sql);
            
            pst.setString(1,username);
            pst.setString(2,password);
            pst.setString(3,firstname);
            pst.setString(4,lastname);
            pst.setInt(5,RoleLookupValues.USER_ROLE);
            pst.setInt(6,UserStatusLookupValues.USER_ENABLED);
            
            int updatedRow = pst.executeUpdate();
            
            if (updatedRow > 0) {
                JOptionPane.showMessageDialog(null,username + " has been added");
                usernameInputField.setText("");
                passwordInputField.setText("");
                firstnameInputField.setText("");
                lastnameInputField.setText("");
                
                MainMenu mainMenu = new MainMenu();
                
                mainMenu.setVisible(true);
                
                setVisible(false);
            }
        }
        
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField firstnameInputField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField lastnameInputField;
    private javax.swing.JPasswordField passwordInputField;
    private javax.swing.JTextField usernameInputField;
    // End of variables declaration//GEN-END:variables
}
